
server:
  port: 8181

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/handifarm?serverTimezone=Asia/Seoul
    username: handi
    password: farm
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    database: mysql
  servlet:
    multipart:
      max-file-size: 10MB # 1개의 파일의 최대 사이즈
      max-request-size: 20MB # 전체 요청의 최대 사이즈
  config:
    import:
      - classpath:keys.yml

logging.level:
  org.hibernate.SQL: debug

# swagger setting
spring-doc:
  swagger-ui:
    path: /myapi.html

logging:
  level:
    org.springframework: DEBUG